/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as RegisterRouteImport } from './routes/_register'
import { Route as RegisterIndexRouteImport } from './routes/_register/index'
import { Route as RegisterSubjectsRouteImport } from './routes/_register/subjects'
import { Route as RegisterFilmRouteImport } from './routes/_register/film'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/_register',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterSubjectsRoute = RegisterSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterFilmRoute = RegisterFilmRouteImport.update({
  id: '/film',
  path: '/film',
  getParentRoute: () => RegisterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/test': typeof TestRoute
  '/film': typeof RegisterFilmRoute
  '/subjects': typeof RegisterSubjectsRoute
  '/': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/test': typeof TestRoute
  '/film': typeof RegisterFilmRoute
  '/subjects': typeof RegisterSubjectsRoute
  '/': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_register': typeof RegisterRouteWithChildren
  '/test': typeof TestRoute
  '/_register/film': typeof RegisterFilmRoute
  '/_register/subjects': typeof RegisterSubjectsRoute
  '/_register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/test' | '/film' | '/subjects' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/test' | '/film' | '/subjects' | '/'
  id:
    | '__root__'
    | '/_register'
    | '/test'
    | '/_register/film'
    | '/_register/subjects'
    | '/_register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RegisterRoute: typeof RegisterRouteWithChildren
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_register': {
      id: '/_register'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_register/': {
      id: '/_register/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/_register/subjects': {
      id: '/_register/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof RegisterSubjectsRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/_register/film': {
      id: '/_register/film'
      path: '/film'
      fullPath: '/film'
      preLoaderRoute: typeof RegisterFilmRouteImport
      parentRoute: typeof RegisterRoute
    }
  }
}

interface RegisterRouteChildren {
  RegisterFilmRoute: typeof RegisterFilmRoute
  RegisterSubjectsRoute: typeof RegisterSubjectsRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterFilmRoute: RegisterFilmRoute,
  RegisterSubjectsRoute: RegisterSubjectsRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RegisterRoute: RegisterRouteWithChildren,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
